apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modia-soknadsstatus-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://modia-soknadsstatus-api.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 15m
      memory: 600Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  startup:
    path: /internal/isReady
    initialDelay: 20
    failureThreshold: 30
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: nav-dev
  leaderElection: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-2-10240
        diskSize: 160
        databases:
          - name: modia-soknadsstatus-api-db
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: ida
          cluster: prod-fss
          namespace: traktor
        - application: modiapersonoversikt-api-q1
          cluster: dev-fss
          namespace: personoversikt
        - application: modiapersonoversikt-api-q0
          cluster: dev-fss
          namespace: personoversikt
        - application: modiapersonoversikt-api
          cluster: dev-gcp
          namespace: personoversikt
    outbound:
      external:
        - host: graph.microsoft.com
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pdl-pip-api.dev-fss-pub.nais.io
        - host: pdl-api-q1.dev-fss-pub.nais.io
        - host: skjermede-personer-pip.intern.dev.nav.no
        - host: unleash.nais.io
        - host: hooks.slack.com
      rules:
        - application: norg2
          namespace: org
        - application: logging
          namespace: nais-system
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
  envFrom:
    - secret: modia-soknadstatus-slackhook
  env:
    - name: APP_NAME
      value: "modia-soknadsstatus-api"
    - name: APP_MODE
      value: "NAIS"
    - name: APP_VERSION
      value: "dev"
    - name: DB_NAME
      value: "modia-soknadsstatus-api-db"
    - name: KAFKA_SOURCE_TOPIC
      value: "personoversikt.modia-soknadsstatus-oppdatering"
    - name: KAFKA_DEAD_LETTER_QUEUE_TOPIC
      value: "personoversikt.modia-soknadsstatus-oppdatering-dlq"
    - name: KAFKA_DEAD_LETTER_QUEUE_CONSUMER_POLL_INTERVAL_MS
      value: "60000"
    - name: KAFKA_DEAD_LETTER_QUEUE_SKIP_TABLE_NAME
      value: "soknadsstatus_api_dlq_event_skip"
    - name: KAFKA_DEAD_LETTER_QUEUE_METRICS_GAUGE_NAME
      value: "modia_soknadsstatus_api_dlq_gauge"
    - name: HENDELSE_CONSUMER_POLL_DURATION_MS
      value: "1000"
    - name: HENDELSE_CONSUMER_RESTART_DELAY_MS
      value: "2000"
    - name: NORG2_URL
      value: "http://norg2.org/norg2"
    - name: PDL_API_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: PDL_API_URL_Q1
      value: "https://pdl-api-q1.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE_Q1
      value: "dev-fss:pdl:pdl-api-q1"
    - name: PDL_PIP_API_URL
      value: "https://pdl-pip-api.dev-fss-pub.nais.io"
    - name: PDL_PIP_SCOPE
      value: dev-fss:pdl:pdl-pip-api
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: "https://skjermede-personer-pip.intern.dev.nav.no"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "dev-gcp:nom:skjermede-personer-pip"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: TILGANGSMASKINEN_URL
      value: "http://populasjonstilgangskontroll.tilgangsmaskin"
    - name: TILGANGSMASKINEN_SCOPE
      value: "dev-gcp:tilgangsmaskin:populasjonstilgangskontroll"
