version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
    labels:
      - dependabot
  - package-ecosystem:  github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: UTC
    labels:
      - dependabot
