rootProject.name = "modia-soknadsstatus"
include("common:jms")
include("common:kafka")
include("common:kafka-stream-transformer")
include("common:dataformat")
include("common:ktor")
include("common:utils")
include("apps:mq-to-kafka")
include("apps:arena-infotrygd-soknadsstatus-transform")
include("apps:modia-soknadsstatus-api")
include("apps:data-generator-app")
include("apps:fp-k9-soknadsstatus-transform")
include("common:filter")
include("tjenestespesifikasjoner:norg-api")
include("tjenestespesifikasjoner:kodeverk-api")
include("tjenestespesifikasjoner:skjermede-personer-pip-api")
include("tjenestespesifikasjoner:pdl-api")
include("tjenestespesifikasjoner:saf-api")
