rootProject.name = "modia-soknadstatus"
include("common:jms")
include("common:kafka")
include("common:kafka-stream-transformer")
include("common:dataformat")
include("common:ktor")
include("apps:mq-to-kafka")
include("apps:infotrygd-soknadstatus-transform")
include("apps:arena-soknadstatus-transform")
include("apps:foreldrepenger-soknadstatus-transform")
include("apps:pleiepenger-soknadstatus-transform")
include("apps:modia-soknadstatus-api")
include("apps:data-generator-app")
include("apps:fp-k9-soknadstatus-transform")
