kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modia-soknadsstatus-kafka-manager
  namespace: personosversikt
  labels:
    team: personoversikt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2023.08.02-07.02-45dfb71 # See https://console.cloud.google.com/artifacts/docker/nais-management-233d/europe-north1/poao/kafka-manager
  port: 8080
  webproxy: true
  ingresses:
    - https://modia-soknadsstatus-kafka-manager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 66069613-0b62-4d9a-8289-5e53b23f5adc
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "personoversikt.modia-soknadsstatus-hendelse",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "personoversikt.modia-soknadsstatus-hendelse-dlq",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "personoversikt.modia-soknadsstatus-arena-infotrygd",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "personoversikt.modia-soknadsstatus-arena-infotrygd-dlq",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "personoversikt.modia-soknadsstatus-oppdatering",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "personoversikt.modia-soknadsstatus-oppdatering-dlq",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }