apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arena-infotrygd-soknadsstatus-transform
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  resources:
    requests:
      cpu: 15m
      memory: 250Mi
    limits:
      memory: 4096Mi
  accessPolicy:
    outbound:
      external:
        - host: hooks.slack.com
      rules:
        - application: logging
          namespace: nais-system
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: arena-infotrygd-soknadsstatus-db
  envFrom:
    - secret: modia-soknadstatus-slackhook
  env:
    - name: APP_NAME
      value: "arena-infotrygd-soknadsstatus-transform"
    - name: APP_MODE
      value: "NAIS"
    - name: APP_VERSION
      value: "prod"
    - name: DB_NAME
      value: "arena-infotrygd-soknadsstatus-db"
    - name: KAFKA_SOURCE_TOPIC
      value: "personoversikt.modia-soknadsstatus-arena-infotrygd-oppdatering"
    - name: KAFKA_TARGET_TOPIC
      value: "personoversikt.modia-soknadsstatus-oppdatering"
    - name: KAFKA_DEAD_LETTER_QUEUE_TOPIC
      value: "personoversikt.modia-soknadsstatus-arena-infotrygd-dlq"
    - name: KAFKA_DEAD_LETTER_QUEUE_CONSUMER_POLL_INTERVAL_MS
      value: "60000"
    - name: KAFKA_DEAD_LETTER_QUEUE_SKIP_TABLE_NAME
      value: "arena_infotrygd_dlq_event_skip"
    - name: KAFKA_DEAD_LETTER_QUEUE_METRICS_GAUGE_NAME
      value: "modia_soknadsstatus_arena_infotrygd_dlq_gauge"
