apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: modia-soknadsstatus-fp-k9-dlq
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    dcat.data.nav.no/title: "personoversikt.modia-soknadsstatus-fp-k9-dlq"
    dcat.data.nav.no/description: "Topic for modia søknadsstatus for oppdateringer som kommer inn til fp-k9-transform som ikke klarer å parses"
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2
    retentionBytes: -1    # Messages will never get deleted because of disk space
    retentionHours: 730  # Messages are stored for 1 month
  acl:
    - team: personoversikt
      application: fp-k9-soknadsstatus-transform
      access: readwrite