apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: modia-soknadsstatus-behandling-oppdatering-dlq
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    dcat.data.nav.no/title: "personoversikt.modia-soknadsstatus-behandling-oppdatering-dlq"
    dcat.data.nav.no/description: "Topic for modia søknadsstatus for oppdateringer som ikke klarer å hente fnr fra pdl (SOB migrering)"
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2
    retentionBytes: -1    # Messages will never get deleted because of disk space
    retentionHours: 730  # Messages are stored for 1 month
  acl:
    - team: personoversikt
      application: modia-soknadsstatus-api
      access: readwrite
    - team: personoversikt
      application: modia-soknadsstatus-kafka-manager
      access: read
