name: ..build.yaml

on:
  workflow_call:
    inputs:
      topic-file-name:
        required: true
        type: string

jobs:
  deploy-topic-to-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy topic to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy henvendelse-oppdatering-melding topic
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/topics/${{ inputs.topic-file-name }}
          VARS: .github/kafka-pools/dev.json

  deploy-topic-to-prod:
    if: github.ref == 'refs/heads/master'
    name: Deploy topic to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy henvendelse-oppdatering-melding topic
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/topics/${{ inputs.topic-file-name }}
          VARS: .github/kafka-pools/prod.json
