name: arena-infotrygd-soknadsstatus-transform

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/.build.yaml
      - .github/workflows/arena-infotrygd-soknadsstatus-transform.yaml
      - common/**
      - gradle/**
      - apps/arena-infotrygd-soknadsstatus-transform/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
