name: arena-infotrygd-soknadsstatus-transform

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - feature/**
      - bugfix/**
    paths:
      - common/**
      - apps/arena-infotrygd-soknadsstatus-transform/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit