name: fp-k9-soknadsstatus-transform

on:
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'Build, test and deploy'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
  push:
    branches:
      - master
    paths:
      - common/**
      - apps/fp-k9-soknadsstatus-transform/**
  pull_request:
    branches:
      - master
    paths:
      - common/**
      - apps/fp-k9-soknadsstatus-transform/**

jobs:
  test:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/.build.yaml
    secrets: inherit

  build:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/.build.yaml
    secrets: inherit