name: modia-soknadsstatus-api

on:
  workflow_dispatch:
  push:
    paths:
      - common/**
      - apps/modia-soknadsstatus-api/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit