name: modia-soknadsstatus-api

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - feature/**
      - bugfix/**
    paths:
      - common/**
      - apps/modia-soknadsstatus-api/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit