name: modia-soknadsstatus-api

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/.build.yaml
      - .github/workflows/modia-soknadsstatus-api.yaml
      - common/**
      - apps/modia-soknadsstatus-api/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit
    permissions:
      packages: write
