name: mq-to-kafka

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
      - feature/**
      - bugfix/**
    paths:
      - common/**
      - apps/mq-to-kafka/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit