name: mq-to-kafka

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/.build.yaml
      - .github/workflows/mq-to-kafka.yaml
      - common/**
      - apps/mq-to-kafka/**

jobs:
  build:
    uses: ./.github/workflows/.build.yaml
    secrets: inherit